program HODLER_Wallet_Desktop;

{$R *.dres}

uses
  SafeDLLPath in 'SafeDLLPath.pas',
  System.StartUpCopy,
  FMX.Forms,
  FMX.Styles,
  uHome in 'homeWindows\uHome.pas' {frmHome},
  misc in 'additionalUnits\misc.pas',
  base58 in 'additionalUnits\base58.pas',
  secp256k1 in 'coinCode\secp256k1.pas',
  Bitcoin in 'coinCode\Bitcoin.pas',
  ZXing.OneD.Code93Reader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.Code93Reader.pas',
  ZXing.OneD.Code128Reader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.Code128Reader.pas',
  ZXing.OneD.EAN13Reader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.EAN13Reader.pas',
  ZXing.OneD.EANManufacturerOrgSupport in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.EANManufacturerOrgSupport.pas',
  ZXing.OneD.ITFReader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.ITFReader.pas',
  ZXing.OneD.OneDReader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.OneDReader.pas',
  ZXing.OneD.UPCEANExtension2Support in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension2Support.pas',
  ZXing.OneD.UPCEANExtension5Support in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension5Support.pas',
  ZXing.OneD.UPCEANExtensionSupport in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtensionSupport.pas',
  ZXing.OneD.UPCEANReader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANReader.pas',
  ZXing.QrCode.QRCodeReader in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\ZXing.QrCode.QRCodeReader.pas',
  ZXing.Datamatrix.DataMatrixReader in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\ZXing.Datamatrix.DataMatrixReader.pas',
  ZXing.QrCode.Internal.DataBlock in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataBlock.pas',
  ZXing.QrCode.Internal.DataMask in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataMask.pas',
  ZXing.QrCode.Internal.DecodedBitStreamParser in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  ZXing.QrCode.Internal.Decoder in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Decoder.pas',
  ZXing.QrCode.Internal.ErrorCorrectionLevel in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  ZXing.QrCode.Internal.FormatInformation in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.FormatInformation.pas',
  ZXing.QrCode.Internal.Mode in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Mode.pas',
  ZXing.QrCode.Internal.QRCodeDecoderMetaData in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  ZXing.QrCode.Internal.Version in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Version.pas',
  ZXing.Datamatrix.Internal.BitMatrixParser in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  ZXing.Datamatrix.Internal.DataBlock in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DataBlock.pas',
  ZXing.Datamatrix.Internal.DecodedBitStreamParser in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  ZXing.Datamatrix.Internal.Decoder in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Decoder.pas',
  ZXing.Datamatrix.Internal.Version in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Version.pas',
  ZXing.QrCode.Internal.BitMatrixParser in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.BitMatrixParser.pas',
  ZXing.QrCode.Internal.AlignmentPattern in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPattern.pas',
  ZXing.QrCode.Internal.AlignmentPatternFinder in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  ZXing.QrCode.Internal.Detector in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.Detector.pas',
  ZXing.QrCode.Internal.FinderPattern in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPattern.pas',
  ZXing.QrCode.Internal.FinderPatternFinder in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternFinder.pas',
  ZXing.QrCode.Internal.FinderPatternInfo in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternInfo.pas',
  ZXing.Datamatrix.Internal.Detector in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.Datamatrix.Internal.Detector.pas',
  ZXing.DecoderResult in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.DecoderResult.pas',
  ZXing.DefaultGridSampler in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.DefaultGridSampler.pas',
  ZXing.Helpers in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Helpers.pas',
  ZXing.MultiFormatReader in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.MultiFormatReader.pas',
  ZXing.ResultMetadataType in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.ResultMetadataType.pas',
  ZXing.StringUtils in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.StringUtils.pas',
  ZXing.BarcodeFormat in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.BarcodeFormat.pas',
  ZXing.Common.BitArray in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Common.BitArray.pas',
  ZXing.Common.BitMatrix in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Common.BitMatrix.pas',
  ZXing.Common.DetectorResult in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Common.DetectorResult.pas',
  ZXing.Common.GridSampler in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Common.GridSampler.pas',
  ZXing.Common.PerspectiveTransform in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Common.PerspectiveTransform.pas',
  ZXing.EncodeHintType in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.EncodeHintType.pas',
  ZXing.Reader in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Reader.pas',
  ZXing.ReadResult in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.ReadResult.pas',
  ZXing.ResultPoint in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.ResultPoint.pas',
  ZXing.Common.Detector.MathUtils in 'additionalUnits\ZXING\Lib\Classes\Common\Detector\ZXing.Common.Detector.MathUtils.pas',
  ZXing.Common.Detector.WhiteRectangleDetector in 'additionalUnits\ZXING\Lib\Classes\Common\Detector\ZXing.Common.Detector.WhiteRectangleDetector.pas',
  ZXing.Common.ReedSolomon.GenericGF in 'additionalUnits\ZXING\Lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.GenericGF.pas',
  ZXing.Common.ReedSolomon.ReedSolomonDecoder in 'additionalUnits\ZXING\Lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  ZXing.BitSource in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.BitSource.pas',
  ZXing.CharacterSetECI in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.CharacterSetECI.pas',
  ZXing.DecodeHintType in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.DecodeHintType.pas',
  ZXing.Binarizer in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.Binarizer.pas',
  ZXing.BinaryBitmap in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.BinaryBitmap.pas',
  ZXing.GlobalHistogramBinarizer in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.GlobalHistogramBinarizer.pas',
  ZXing.HybridBinarizer in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.HybridBinarizer.pas',
  ZXing.BaseLuminanceSource in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.BaseLuminanceSource.pas',
  ZXing.InvertedLuminanceSource in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.InvertedLuminanceSource.pas',
  ZXing.LuminanceSource in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.LuminanceSource.pas',
  ZXing.PlanarYUVLuminanceSource in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.PlanarYUVLuminanceSource.pas',
  ZXing.RGBLuminanceSource in 'additionalUnits\ZXING\Lib\Classes\Filtering\ZXing.RGBLuminanceSource.pas',
  ZXing.ScanManager in 'additionalUnits\ZXING\Lib\Classes\ZXing.ScanManager.pas',
  ZXing.Common.BitArrayImplementation in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.Common.BitArrayImplementation.pas',
  ZXing.ResultPointImplementation in 'additionalUnits\ZXING\Lib\Classes\Common\ZXing.ResultPointImplementation.pas',
  ZXing.QrCode.Internal.AlignmentPatternImplementation in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  ZXing.QrCode.Internal.FinderPatternImplementation in 'additionalUnits\ZXING\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  ZXIng.ByteSegments in 'additionalUnits\ZXING\Lib\Classes\Common\ZXIng.ByteSegments.pas',
  ZXing.OneD.EAN8Reader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.EAN8Reader.pas',
  ZXing.OneD.UPCAReader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.UPCAReader.pas',
  ZXing.OneD.UPCEReader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEReader.pas',
  ZXing.OneD.Code39Reader in 'additionalUnits\ZXING\Lib\Classes\1D Barcodes\ZXing.OneD.Code39Reader.pas',
  DelphiZXIngQRCode in 'additionalUnits\ZXING\DelphiZXIngQRCode.pas',
  transactions in 'coinCode\transactions.pas',
  btypes in 'additionalUnits\KECCAK\btypes.pas',
  keccak_n in 'additionalUnits\KECCAK\keccak_n.pas',
  Ethereum in 'coinCode\Ethereum.pas',
  coinData in 'coinCode\coinData.pas',
  tokenData in 'coinCode\tokenData.pas',
  bech32 in 'additionalUnits\bech32.pas',
  FMX.Ani in 'FMX.Ani.pas',
  DW.ThreadedTimer in 'DW.ThreadedTimer.pas',
  cryptoCurrencyData in 'coinCode\cryptoCurrencyData.pas',
  SyncThr in 'additionalUnits\SyncThr.pas',
  languages in 'Languages\languages.pas',
  CurrencyConverter in 'additionalUnits\CurrencyConverter.pas',
  WIF in 'additionalUnits\WIF.pas',
  AccountData in 'additionalUnits\AccountData.pas',
  WalletStructureData in 'WalletStructureData.pas',
  {$IF NOT DEFINED(LINUX)}
  Windows,
  {$ENDIF }
  FMX.Types,
  WalletViewRelated in 'additionalUnits\WalletViewRelated.pas',
  BackupRelated in 'additionalUnits\BackupRelated.pas',
  AccountRelated in 'additionalUnits\AccountRelated.pas',
  QRRelated in 'additionalUnits\QRRelated.pas',
  FileManagerRelated in 'additionalUnits\FileManagerRelated.pas',
  TCopyableEditData in 'components\TCopyableEditData.pas',
  TCopyableLabelData in 'components\TCopyableLabelData.pas',
  TRotateImageData in 'components\TRotateImageData.pas',
  TImageTextButtonData in 'components\TImageTextButtonData.pas',
  CompilerAndRTLVersions in 'additionalUnits\bi\CompilerAndRTLVersions.pas',
  Velthuis.BigDecimals in 'additionalUnits\bi\Velthuis.BigDecimals.pas',
  Velthuis.BigIntegers in 'additionalUnits\bi\Velthuis.BigIntegers.pas',
  Velthuis.BigIntegers.Primes in 'additionalUnits\bi\Velthuis.BigIntegers.Primes.pas',
  Velthuis.BigRationals in 'additionalUnits\bi\Velthuis.BigRationals.pas',
  Velthuis.ExactFloatStrings in 'additionalUnits\bi\Velthuis.ExactFloatStrings.pas',
  Velthuis.FloatUtils in 'additionalUnits\bi\Velthuis.FloatUtils.pas',
  Velthuis.Loggers in 'additionalUnits\bi\Velthuis.Loggers.pas',
  Velthuis.Numerics in 'additionalUnits\bi\Velthuis.Numerics.pas',
  Velthuis.RandomNumbers in 'additionalUnits\bi\Velthuis.RandomNumbers.pas',
  Velthuis.Sizes in 'additionalUnits\bi\Velthuis.Sizes.pas',
  Velthuis.StrConsts in 'additionalUnits\bi\Velthuis.StrConsts.pas',
  Velthuis.XorShifts in 'additionalUnits\bi\Velthuis.XorShifts.pas',
  ClpECGost3410NamedCurves in 'additionalUnits\CryptoLib\src\Asn1\CryptoPro\ClpECGost3410NamedCurves.pas',
  ClpCryptoProObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\CryptoPro\ClpCryptoProObjectIdentifiers.pas',
  ClpNistObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Nist\ClpNistObjectIdentifiers.pas',
  ClpOiwObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Oiw\ClpOiwObjectIdentifiers.pas',
  ClpPkcsObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Pkcs\ClpPkcsObjectIdentifiers.pas',
  ClpRosstandartObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\RossStandart\ClpRosstandartObjectIdentifiers.pas',
  ClpSecNamedCurves in 'additionalUnits\CryptoLib\src\Asn1\Sec\ClpSecNamedCurves.pas',
  ClpSecObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Sec\ClpSecObjectIdentifiers.pas',
  ClpTeleTrusTObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\TeleTrust\ClpTeleTrusTObjectIdentifiers.pas',
  ClpECNamedCurveTable in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpECNamedCurveTable.pas',
  ClpX9Curve in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9Curve.pas',
  ClpX9ECParameters in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9ECParameters.pas',
  ClpX9ECParametersHolder in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9ECParametersHolder.pas',
  ClpX9ECPoint in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9ECPoint.pas',
  ClpX9FieldElement in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9FieldElement.pas',
  ClpX9FieldID in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9FieldID.pas',
  ClpX9IntegerConverter in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9IntegerConverter.pas',
  ClpX9ObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\X9\ClpX9ObjectIdentifiers.pas',
  ClpAsn1Encodable in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Encodable.pas',
  ClpAsn1EncodableVector in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1EncodableVector.pas',
  ClpAsn1InputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1InputStream.pas',
  ClpAsn1Null in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Null.pas',
  ClpAsn1Object in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Object.pas',
  ClpAsn1OctetString in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1OctetString.pas',
  ClpAsn1OutputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1OutputStream.pas',
  ClpAsn1Sequence in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Sequence.pas',
  ClpAsn1Set in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Set.pas',
  ClpAsn1StreamParser in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1StreamParser.pas',
  ClpAsn1TaggedObject in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1TaggedObject.pas',
  ClpAsn1Tags in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Tags.pas',
  ClpBerApplicationSpecific in 'additionalUnits\CryptoLib\src\Asn1\ClpBerApplicationSpecific.pas',
  ClpBerApplicationSpecificParser in 'additionalUnits\CryptoLib\src\Asn1\ClpBerApplicationSpecificParser.pas',
  ClpBerBitString in 'additionalUnits\CryptoLib\src\Asn1\ClpBerBitString.pas',
  ClpBerNull in 'additionalUnits\CryptoLib\src\Asn1\ClpBerNull.pas',
  ClpBerOctetString in 'additionalUnits\CryptoLib\src\Asn1\ClpBerOctetString.pas',
  ClpBerOctetStringParser in 'additionalUnits\CryptoLib\src\Asn1\ClpBerOctetStringParser.pas',
  ClpBerOutputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpBerOutputStream.pas',
  ClpBerSequence in 'additionalUnits\CryptoLib\src\Asn1\ClpBerSequence.pas',
  ClpBerSequenceParser in 'additionalUnits\CryptoLib\src\Asn1\ClpBerSequenceParser.pas',
  ClpBerSet in 'additionalUnits\CryptoLib\src\Asn1\ClpBerSet.pas',
  ClpBerSetParser in 'additionalUnits\CryptoLib\src\Asn1\ClpBerSetParser.pas',
  ClpBerTaggedObject in 'additionalUnits\CryptoLib\src\Asn1\ClpBerTaggedObject.pas',
  ClpBerTaggedObjectParser in 'additionalUnits\CryptoLib\src\Asn1\ClpBerTaggedObjectParser.pas',
  ClpConstructedOctetStream in 'additionalUnits\CryptoLib\src\Asn1\ClpConstructedOctetStream.pas',
  ClpDefiniteLengthInputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpDefiniteLengthInputStream.pas',
  ClpDerApplicationSpecific in 'additionalUnits\CryptoLib\src\Asn1\ClpDerApplicationSpecific.pas',
  ClpDerBitString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerBitString.pas',
  ClpDerBmpString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerBmpString.pas',
  ClpDerBoolean in 'additionalUnits\CryptoLib\src\Asn1\ClpDerBoolean.pas',
  ClpDerEnumerated in 'additionalUnits\CryptoLib\src\Asn1\ClpDerEnumerated.pas',
  ClpDerExternal in 'additionalUnits\CryptoLib\src\Asn1\ClpDerExternal.pas',
  ClpDerExternalParser in 'additionalUnits\CryptoLib\src\Asn1\ClpDerExternalParser.pas',
  ClpDerGeneralString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerGeneralString.pas',
  ClpDerGraphicString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerGraphicString.pas',
  ClpDerIA5String in 'additionalUnits\CryptoLib\src\Asn1\ClpDerIA5String.pas',
  ClpDerInteger in 'additionalUnits\CryptoLib\src\Asn1\ClpDerInteger.pas',
  ClpDerNull in 'additionalUnits\CryptoLib\src\Asn1\ClpDerNull.pas',
  ClpDerNumericString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerNumericString.pas',
  ClpDerObjectIdentifier in 'additionalUnits\CryptoLib\src\Asn1\ClpDerObjectIdentifier.pas',
  ClpDerOctetString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerOctetString.pas',
  ClpDerOctetStringParser in 'additionalUnits\CryptoLib\src\Asn1\ClpDerOctetStringParser.pas',
  ClpDerOutputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpDerOutputStream.pas',
  ClpDerPrintableString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerPrintableString.pas',
  ClpDerSequence in 'additionalUnits\CryptoLib\src\Asn1\ClpDerSequence.pas',
  ClpDerSequenceParser in 'additionalUnits\CryptoLib\src\Asn1\ClpDerSequenceParser.pas',
  ClpDerSet in 'additionalUnits\CryptoLib\src\Asn1\ClpDerSet.pas',
  ClpDerSetParser in 'additionalUnits\CryptoLib\src\Asn1\ClpDerSetParser.pas',
  ClpDerStringBase in 'additionalUnits\CryptoLib\src\Asn1\ClpDerStringBase.pas',
  ClpDerT61String in 'additionalUnits\CryptoLib\src\Asn1\ClpDerT61String.pas',
  ClpDerTaggedObject in 'additionalUnits\CryptoLib\src\Asn1\ClpDerTaggedObject.pas',
  ClpDerUniversalString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerUniversalString.pas',
  ClpDerUtf8String in 'additionalUnits\CryptoLib\src\Asn1\ClpDerUtf8String.pas',
  ClpDerVideotexString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerVideotexString.pas',
  ClpDerVisibleString in 'additionalUnits\CryptoLib\src\Asn1\ClpDerVisibleString.pas',
  ClpIndefiniteLengthInputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpIndefiniteLengthInputStream.pas',
  ClpLimitedInputStream in 'additionalUnits\CryptoLib\src\Asn1\ClpLimitedInputStream.pas',
  ClpOidTokenizer in 'additionalUnits\CryptoLib\src\Asn1\ClpOidTokenizer.pas',
  ClpECKeyPairGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpECKeyPairGenerator.pas',
  ClpECDomainParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpECDomainParameters.pas',
  ClpECKeyGenerationParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpECKeyGenerationParameters.pas',
  ClpECKeyParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpECKeyParameters.pas',
  ClpECPrivateKeyParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpECPrivateKeyParameters.pas',
  ClpECPublicKeyParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpECPublicKeyParameters.pas',
  ClpCryptoApiRandomGenerator in 'additionalUnits\CryptoLib\src\Crypto\Prng\ClpCryptoApiRandomGenerator.pas',
  ClpDigestRandomGenerator in 'additionalUnits\CryptoLib\src\Crypto\Prng\ClpDigestRandomGenerator.pas',
  ClpAsymmetricCipherKeyPair in 'additionalUnits\CryptoLib\src\Crypto\ClpAsymmetricCipherKeyPair.pas',
  ClpAsymmetricKeyParameter in 'additionalUnits\CryptoLib\src\Crypto\ClpAsymmetricKeyParameter.pas',
  ClpKeyGenerationParameters in 'additionalUnits\CryptoLib\src\Crypto\ClpKeyGenerationParameters.pas',
  ClpIAbstractECMultiplier in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAbstractECMultiplier.pas',
  ClpIAsn1ApplicationSpecificParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1ApplicationSpecificParser.pas',
  ClpIAsn1Choice in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1Choice.pas',
  ClpIAsn1EncodableVector in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1EncodableVector.pas',
  ClpIAsn1Null in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1Null.pas',
  ClpIAsn1OctetString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1OctetString.pas',
  ClpIAsn1OctetStringParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1OctetStringParser.pas',
  ClpIAsn1Sequence in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1Sequence.pas',
  ClpIAsn1SequenceParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1SequenceParser.pas',
  ClpIAsn1Set in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1Set.pas',
  ClpIAsn1SetParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1SetParser.pas',
  ClpIAsn1StreamParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1StreamParser.pas',
  ClpIAsn1String in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1String.pas',
  ClpIAsn1TaggedObject in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1TaggedObject.pas',
  ClpIAsn1TaggedObjectParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1TaggedObjectParser.pas',
  ClpIAsymmetricCipherKeyPair in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsymmetricCipherKeyPair.pas',
  ClpIAsymmetricCipherKeyPairGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsymmetricCipherKeyPairGenerator.pas',
  ClpIAsymmetricKeyParameter in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsymmetricKeyParameter.pas',
  ClpIBerApplicationSpecific in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerApplicationSpecific.pas',
  ClpIBerApplicationSpecificParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerApplicationSpecificParser.pas',
  ClpIBerBitString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerBitString.pas',
  ClpIBerNull in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerNull.pas',
  ClpIBerOctetString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerOctetString.pas',
  ClpIBerOctetStringParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerOctetStringParser.pas',
  ClpIBerSequence in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerSequence.pas',
  ClpIBerSequenceParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerSequenceParser.pas',
  ClpIBerSet in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerSet.pas',
  ClpIBerSetParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerSetParser.pas',
  ClpIBerTaggedObject in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerTaggedObject.pas',
  ClpIBerTaggedObjectParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerTaggedObjectParser.pas',
  ClpICipherParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpICipherParameters.pas',
  ClpICryptoApiRandomGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpICryptoApiRandomGenerator.pas',
  ClpIDerApplicationSpecific in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerApplicationSpecific.pas',
  ClpIDerBitString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerBitString.pas',
  ClpIDerBmpString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerBmpString.pas',
  ClpIDerBoolean in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerBoolean.pas',
  ClpIDerEnumerated in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerEnumerated.pas',
  ClpIDerExternal in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerExternal.pas',
  ClpIDerExternalParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerExternalParser.pas',
  ClpIDerGeneralString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerGeneralString.pas',
  ClpIDerGraphicString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerGraphicString.pas',
  ClpIDerIA5String in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerIA5String.pas',
  ClpIDerInteger in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerInteger.pas',
  ClpIDerNull in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerNull.pas',
  ClpIDerNumericString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerNumericString.pas',
  ClpIDerObjectIdentifier in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerObjectIdentifier.pas',
  ClpIDerOctetString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerOctetString.pas',
  ClpIDerOctetStringParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerOctetStringParser.pas',
  ClpIDerPrintableString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerPrintableString.pas',
  ClpIDerSequence in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerSequence.pas',
  ClpIDerSequenceParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerSequenceParser.pas',
  ClpIDerSet in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerSet.pas',
  ClpIDerSetParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerSetParser.pas',
  ClpIDerStringBase in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerStringBase.pas',
  ClpIDerT61String in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerT61String.pas',
  ClpIDerTaggedObject in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerTaggedObject.pas',
  ClpIDerUniversalString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerUniversalString.pas',
  ClpIDerUtf8String in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerUtf8String.pas',
  ClpIDerVideotexString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerVideotexString.pas',
  ClpIDerVisibleString in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerVisibleString.pas',
  ClpIDigestRandomGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDigestRandomGenerator.pas',
  ClpIECDomainParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECDomainParameters.pas',
  ClpIECFieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECFieldElement.pas',
  ClpIECInterface in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECInterface.pas',
  ClpIECKeyGenerationParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECKeyGenerationParameters.pas',
  ClpIECKeyPairGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECKeyPairGenerator.pas',
  ClpIECKeyParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECKeyParameters.pas',
  ClpIECPrivateKeyParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECPrivateKeyParameters.pas',
  ClpIECPublicKeyParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECPublicKeyParameters.pas',
  ClpIExtensionField in 'additionalUnits\CryptoLib\src\Interfaces\ClpIExtensionField.pas',
  ClpIFiniteField in 'additionalUnits\CryptoLib\src\Interfaces\ClpIFiniteField.pas',
  ClpIFixedPointCombMultiplier in 'additionalUnits\CryptoLib\src\Interfaces\ClpIFixedPointCombMultiplier.pas',
  ClpIFixedPointPreCompInfo in 'additionalUnits\CryptoLib\src\Interfaces\ClpIFixedPointPreCompInfo.pas',
  ClpIGlvEndomorphism in 'additionalUnits\CryptoLib\src\Interfaces\ClpIGlvEndomorphism.pas',
  ClpIGlvTypeBEndomorphism in 'additionalUnits\CryptoLib\src\Interfaces\ClpIGlvTypeBEndomorphism.pas',
  ClpIGlvTypeBParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIGlvTypeBParameters.pas',
  ClpIKeyGenerationParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIKeyGenerationParameters.pas',
  ClpIOidTokenizer in 'additionalUnits\CryptoLib\src\Interfaces\ClpIOidTokenizer.pas',
  ClpIPCGRandomNumberGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPCGRandomNumberGenerator.pas',
  ClpIPolynomial in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPolynomial.pas',
  ClpIPolynomialExtensionField in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPolynomialExtensionField.pas',
  ClpIPreCompInfo in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPreCompInfo.pas',
  ClpIProxiedInterface in 'additionalUnits\CryptoLib\src\Interfaces\ClpIProxiedInterface.pas',
  ClpIRandom in 'additionalUnits\CryptoLib\src\Interfaces\ClpIRandom.pas',
  ClpIRandomGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIRandomGenerator.pas',
  ClpIRandomNumberGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIRandomNumberGenerator.pas',
  ClpIScaleXPointMap in 'additionalUnits\CryptoLib\src\Interfaces\ClpIScaleXPointMap.pas',
  ClpISecureRandom in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecureRandom.pas',
  ClpIWNafPreCompInfo in 'additionalUnits\CryptoLib\src\Interfaces\ClpIWNafPreCompInfo.pas',
  ClpIX9Curve in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX9Curve.pas',
  ClpIX9ECParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX9ECParameters.pas',
  ClpIX9ECParametersHolder in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX9ECParametersHolder.pas',
  ClpIX9ECPoint in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX9ECPoint.pas',
  ClpIX9FieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX9FieldElement.pas',
  ClpIX9FieldID in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX9FieldID.pas',
  ClpGlvTypeBEndomorphism in 'additionalUnits\CryptoLib\src\Math\EC\Endo\ClpGlvTypeBEndomorphism.pas',
  ClpGlvTypeBParameters in 'additionalUnits\CryptoLib\src\Math\EC\Endo\ClpGlvTypeBParameters.pas',
  ClpAbstractECMultiplier in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpAbstractECMultiplier.pas',
  ClpFixedPointCombMultiplier in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpFixedPointCombMultiplier.pas',
  ClpFixedPointPreCompInfo in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpFixedPointPreCompInfo.pas',
  ClpFixedPointUtilities in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpFixedPointUtilities.pas',
  ClpWNafPreCompInfo in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpWNafPreCompInfo.pas',
  ClpECAlgorithms in 'additionalUnits\CryptoLib\src\Math\EC\ClpECAlgorithms.pas',
  ClpECCurve in 'additionalUnits\CryptoLib\src\Math\EC\ClpECCurve.pas',
  ClpECFieldElement in 'additionalUnits\CryptoLib\src\Math\EC\ClpECFieldElement.pas',
  ClpECPoint in 'additionalUnits\CryptoLib\src\Math\EC\ClpECPoint.pas',
  ClpLongArray in 'additionalUnits\CryptoLib\src\Math\EC\ClpLongArray.pas',
  ClpScaleXPointMap in 'additionalUnits\CryptoLib\src\Math\EC\ClpScaleXPointMap.pas',
  ClpBigInteger in 'additionalUnits\CryptoLib\src\Math\ClpBigInteger.pas',
  ClpDigestUtilities in 'additionalUnits\CryptoLib\src\Security\ClpDigestUtilities.pas',
  ClpRandom in 'additionalUnits\CryptoLib\src\Security\ClpRandom.pas',
  ClpSecureRandom in 'additionalUnits\CryptoLib\src\Security\ClpSecureRandom.pas',
  ClpCollectionUtilities in 'additionalUnits\CryptoLib\src\Utils\Collections\ClpCollectionUtilities.pas',
  ClpBase64 in 'additionalUnits\CryptoLib\src\Utils\Encoders\ClpBase64.pas',
  ClpHex in 'additionalUnits\CryptoLib\src\Utils\Encoders\ClpHex.pas',
  ClpStreamHelper in 'additionalUnits\CryptoLib\src\Utils\Helpers\ClpStreamHelper.pas',
  ClpBaseInputStream in 'additionalUnits\CryptoLib\src\Utils\IO\ClpBaseInputStream.pas',
  ClpFilterStream in 'additionalUnits\CryptoLib\src\Utils\IO\ClpFilterStream.pas',
  ClpStreams in 'additionalUnits\CryptoLib\src\Utils\IO\ClpStreams.pas',
  ClpPcgRandomMinimal in 'additionalUnits\CryptoLib\src\Utils\Randoms\ClpPcgRandomMinimal.pas',
  ClpPCGRandomNumberGenerator in 'additionalUnits\CryptoLib\src\Utils\Rng\ClpPCGRandomNumberGenerator.pas',
  ClpRandomNumberGenerator in 'additionalUnits\CryptoLib\src\Utils\Rng\ClpRandomNumberGenerator.pas',
  ClpArrayUtils in 'additionalUnits\CryptoLib\src\Utils\ClpArrayUtils.pas',
  ClpBitConverter in 'additionalUnits\CryptoLib\src\Utils\ClpBitConverter.pas',
  ClpBits in 'additionalUnits\CryptoLib\src\Utils\ClpBits.pas',
  ClpConverters in 'additionalUnits\CryptoLib\src\Utils\ClpConverters.pas',
  ClpCryptoLibTypes in 'additionalUnits\CryptoLib\src\Utils\ClpCryptoLibTypes.pas',
  ClpTimes in 'additionalUnits\CryptoLib\src\Utils\ClpTimes.pas',
  ClpWNafUtilities in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpWNafUtilities.pas',
  ClpBigIntegers in 'additionalUnits\CryptoLib\src\Utils\ClpBigIntegers.pas',
  ClpMod in 'additionalUnits\CryptoLib\src\Math\Raw\ClpMod.pas',
  ClpNat in 'additionalUnits\CryptoLib\src\Math\Raw\ClpNat.pas',
  ClpNumberStyles in 'additionalUnits\CryptoLib\src\Math\ClpNumberStyles.pas',
  ClpParametersWithRandom in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpParametersWithRandom.pas',
  ClpIParametersWithRandom in 'additionalUnits\CryptoLib\src\Interfaces\ClpIParametersWithRandom.pas',
  ClpIDsa in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsa.pas',
  ClpIDsaKCalculator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaKCalculator.pas',
  ClpISigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpISigner.pas',
  ClpRandomDsaKCalculator in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpRandomDsaKCalculator.pas',
  ClpIRandomDsaKCalculator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIRandomDsaKCalculator.pas',
  ClpECDsaSigner in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpECDsaSigner.pas',
  ClpIECDsaSigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECDsaSigner.pas',
  ClpDsaDigestSigner in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpDsaDigestSigner.pas',
  ClpIDsaDigestSigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaDigestSigner.pas',
  ClpSignerUtilities in 'additionalUnits\CryptoLib\src\Security\ClpSignerUtilities.pas',
  ClpZTauElement in 'additionalUnits\CryptoLib\src\Math\EC\Abc\ClpZTauElement.pas',
  ClpIZTauElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpIZTauElement.pas',
  ClpSimpleBigDecimal in 'additionalUnits\CryptoLib\src\Math\EC\Abc\ClpSimpleBigDecimal.pas',
  ClpTnaf in 'additionalUnits\CryptoLib\src\Math\EC\Abc\ClpTnaf.pas',
  ClpGlvMultiplier in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpGlvMultiplier.pas',
  ClpIGlvMultiplier in 'additionalUnits\CryptoLib\src\Interfaces\ClpIGlvMultiplier.pas',
  ClpWTauNafMultiplier in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpWTauNafMultiplier.pas',
  ClpIWTauNafMultiplier in 'additionalUnits\CryptoLib\src\Interfaces\ClpIWTauNafMultiplier.pas',
  ClpWTauNafPreCompInfo in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpWTauNafPreCompInfo.pas',
  ClpIWTauNafPreCompInfo in 'additionalUnits\CryptoLib\src\Interfaces\ClpIWTauNafPreCompInfo.pas',
  ClpWNafL2RMultiplier in 'additionalUnits\CryptoLib\src\Math\EC\Multiplier\ClpWNafL2RMultiplier.pas',
  ClpIWNafL2RMultiplier in 'additionalUnits\CryptoLib\src\Interfaces\ClpIWNafL2RMultiplier.pas',
  ClpGF2Polynomial in 'additionalUnits\CryptoLib\src\Math\Field\ClpGF2Polynomial.pas',
  ClpIGF2Polynomial in 'additionalUnits\CryptoLib\src\Interfaces\ClpIGF2Polynomial.pas',
  ClpGenericPolynomialExtensionField in 'additionalUnits\CryptoLib\src\Math\Field\ClpGenericPolynomialExtensionField.pas',
  ClpIGenericPolynomialExtensionField in 'additionalUnits\CryptoLib\src\Interfaces\ClpIGenericPolynomialExtensionField.pas',
  ClpPrimeField in 'additionalUnits\CryptoLib\src\Math\Field\ClpPrimeField.pas',
  ClpIPrimeField in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPrimeField.pas',
  ClpFiniteFields in 'additionalUnits\CryptoLib\src\Math\Field\ClpFiniteFields.pas',
  ClpOSRandomNumberGenerator in 'additionalUnits\CryptoLib\src\Utils\Rng\ClpOSRandomNumberGenerator.pas',
  ClpIOSRandomNumberGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIOSRandomNumberGenerator.pas',
  ClpOSRandom in 'additionalUnits\CryptoLib\src\Utils\Randoms\ClpOSRandom.pas',
  ClpStreamSorter in 'additionalUnits\CryptoLib\src\Utils\ClpStreamSorter.pas',
  ClpAsn1Generator in 'additionalUnits\CryptoLib\src\Asn1\ClpAsn1Generator.pas',
  ClpIAsn1Generator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAsn1Generator.pas',
  ClpDerGenerator in 'additionalUnits\CryptoLib\src\Asn1\ClpDerGenerator.pas',
  ClpIDerGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerGenerator.pas',
  ClpDerSequenceGenerator in 'additionalUnits\CryptoLib\src\Asn1\ClpDerSequenceGenerator.pas',
  ClpIDerSequenceGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerSequenceGenerator.pas',
  ClpBerGenerator in 'additionalUnits\CryptoLib\src\Asn1\ClpBerGenerator.pas',
  ClpIBerGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerGenerator.pas',
  ClpIBerSequenceGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBerSequenceGenerator.pas',
  ClpBerSequenceGenerator in 'additionalUnits\CryptoLib\src\Asn1\ClpBerSequenceGenerator.pas',
  ClpSetWeakRef in 'additionalUnits\CryptoLib\src\Utils\ClpSetWeakRef.pas',
  ClpCipherUtilities in 'additionalUnits\CryptoLib\src\Security\ClpCipherUtilities.pas',
  ClpIBufferedCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBufferedCipher.pas',
  ClpIBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBlockCipher.pas',
  ClpIBlockCipherPadding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBlockCipherPadding.pas',
  ClpPkcs7Padding in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpPkcs7Padding.pas',
  ClpIPkcs7Padding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPkcs7Padding.pas',
  ClpCbcBlockCipher in 'additionalUnits\CryptoLib\src\Crypto\Modes\ClpCbcBlockCipher.pas',
  ClpICbcBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpICbcBlockCipher.pas',
  ClpParametersWithIV in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpParametersWithIV.pas',
  ClpIParametersWithIV in 'additionalUnits\CryptoLib\src\Interfaces\ClpIParametersWithIV.pas',
  ClpKeyParameter in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpKeyParameter.pas',
  ClpIKeyParameter in 'additionalUnits\CryptoLib\src\Interfaces\ClpIKeyParameter.pas',
  ClpBufferedCipherBase in 'additionalUnits\CryptoLib\src\Crypto\ClpBufferedCipherBase.pas',
  ClpIBufferedCipherBase in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBufferedCipherBase.pas',
  ClpBufferedBlockCipher in 'additionalUnits\CryptoLib\src\Crypto\ClpBufferedBlockCipher.pas',
  ClpIBufferedBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBufferedBlockCipher.pas',
  ClpCheck in 'additionalUnits\CryptoLib\src\Utils\ClpCheck.pas',
  ClpPaddedBufferedBlockCipher in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpPaddedBufferedBlockCipher.pas',
  ClpIPaddedBufferedBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPaddedBufferedBlockCipher.pas',
  ClpGeneratorUtilities in 'additionalUnits\CryptoLib\src\Security\ClpGeneratorUtilities.pas',
  ClpParameterUtilities in 'additionalUnits\CryptoLib\src\Security\ClpParameterUtilities.pas',
  ClpAesEngine in 'additionalUnits\CryptoLib\src\Crypto\Engines\ClpAesEngine.pas',
  ClpIAesEngine in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAesEngine.pas',
  ClpECDHBasicAgreement in 'additionalUnits\CryptoLib\src\Crypto\Agreement\ClpECDHBasicAgreement.pas',
  ClpIBasicAgreement in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBasicAgreement.pas',
  ClpIECDHBasicAgreement in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECDHBasicAgreement.pas',
  ClpIESParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpIESParameters.pas',
  ClpIIESParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIIESParameters.pas',
  ClpIESWithCipherParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpIESWithCipherParameters.pas',
  ClpIIESWithCipherParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIIESWithCipherParameters.pas',
  ClpIDerivationParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerivationParameters.pas',
  ClpIDerivationFunction in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDerivationFunction.pas',
  ClpKdfParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpKdfParameters.pas',
  ClpIKdfParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIKdfParameters.pas',
  ClpIso18033KdfParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpIso18033KdfParameters.pas',
  ClpIIso18033KdfParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIIso18033KdfParameters.pas',
  ClpBaseKdfBytesGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpBaseKdfBytesGenerator.pas',
  ClpIBaseKdfBytesGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIBaseKdfBytesGenerator.pas',
  ClpKdf2BytesGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpKdf2BytesGenerator.pas',
  ClpIKdf2BytesGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIKdf2BytesGenerator.pas',
  ClpIKeyParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIKeyParser.pas',
  ClpEphemeralKeyPair in 'additionalUnits\CryptoLib\src\Crypto\ClpEphemeralKeyPair.pas',
  ClpIEphemeralKeyPair in 'additionalUnits\CryptoLib\src\Interfaces\ClpIEphemeralKeyPair.pas',
  ClpEphemeralKeyPairGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpEphemeralKeyPairGenerator.pas',
  ClpIEphemeralKeyPairGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIEphemeralKeyPairGenerator.pas',
  ClpKeyEncoder in 'additionalUnits\CryptoLib\src\Crypto\ClpKeyEncoder.pas',
  ClpIKeyEncoder in 'additionalUnits\CryptoLib\src\Interfaces\ClpIKeyEncoder.pas',
  ClpIESCipher in 'additionalUnits\CryptoLib\src\Crypto\ClpIESCipher.pas',
  ClpIIESCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpIIESCipher.pas',
  ClpECIESPublicKeyParser in 'additionalUnits\CryptoLib\src\Crypto\Parsers\ClpECIESPublicKeyParser.pas',
  ClpIECIESPublicKeyParser in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECIESPublicKeyParser.pas',
  ClpZeroBytePadding in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpZeroBytePadding.pas',
  ClpIZeroBytePadding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIZeroBytePadding.pas',
  ClpIESEngine in 'additionalUnits\CryptoLib\src\Crypto\Engines\ClpIESEngine.pas',
  ClpIIESEngine in 'additionalUnits\CryptoLib\src\Interfaces\ClpIIESEngine.pas',
  ClpPascalCoinIESEngine in 'additionalUnits\CryptoLib\src\Crypto\Engines\ClpPascalCoinIESEngine.pas',
  ClpIPascalCoinIESEngine in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPascalCoinIESEngine.pas',
  ClpPascalCoinECIESKdfBytesGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpPascalCoinECIESKdfBytesGenerator.pas',
  ClpIPascalCoinECIESKdfBytesGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPascalCoinECIESKdfBytesGenerator.pas',
  ClpISO10126d2Padding in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpISO10126d2Padding.pas',
  ClpIISO10126d2Padding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIISO10126d2Padding.pas',
  ClpISO7816d4Padding in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpISO7816d4Padding.pas',
  ClpIISO7816d4Padding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIISO7816d4Padding.pas',
  ClpTTBCPadding in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpTTBCPadding.pas',
  ClpITBCPadding in 'additionalUnits\CryptoLib\src\Interfaces\ClpITBCPadding.pas',
  ClpX923Padding in 'additionalUnits\CryptoLib\src\Crypto\Paddings\ClpX923Padding.pas',
  ClpIX923Padding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIX923Padding.pas',
  ClpCfbBlockCipher in 'additionalUnits\CryptoLib\src\Crypto\Modes\ClpCfbBlockCipher.pas',
  ClpICfbBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpICfbBlockCipher.pas',
  ClpOfbBlockCipher in 'additionalUnits\CryptoLib\src\Crypto\Modes\ClpOfbBlockCipher.pas',
  ClpIOfbBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpIOfbBlockCipher.pas',
  ClpSicBlockCipher in 'additionalUnits\CryptoLib\src\Crypto\Modes\ClpSicBlockCipher.pas',
  ClpISicBlockCipher in 'additionalUnits\CryptoLib\src\Interfaces\ClpISicBlockCipher.pas',
  ClpIDigest in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDigest.pas',
  ClpIMac in 'additionalUnits\CryptoLib\src\Interfaces\ClpIMac.pas',
  ClpStringUtils in 'additionalUnits\CryptoLib\src\Utils\ClpStringUtils.pas',
  ClpCipherKeyGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpCipherKeyGenerator.pas',
  ClpICipherKeyGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpICipherKeyGenerator.pas',
  ClpHMac in 'additionalUnits\CryptoLib\src\Crypto\Macs\ClpHMac.pas',
  ClpIHMac in 'additionalUnits\CryptoLib\src\Interfaces\ClpIHMac.pas',
  ClpMacUtilities in 'additionalUnits\CryptoLib\src\Security\ClpMacUtilities.pas',
  ClpIanaObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Iana\ClpIanaObjectIdentifiers.pas',
  ClpMiscObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Misc\ClpMiscObjectIdentifiers.pas',
  ClpPbeParametersGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpPbeParametersGenerator.pas',
  ClpIPbeParametersGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPbeParametersGenerator.pas',
  ClpPkcs5S2ParametersGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpPkcs5S2ParametersGenerator.pas',
  ClpIPkcs5S2ParametersGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPkcs5S2ParametersGenerator.pas',
  ClpECNRSigner in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpECNRSigner.pas',
  ClpIECNRSigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECNRSigner.pas',
  ClpDsaValidationParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaValidationParameters.pas',
  ClpIDsaValidationParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaValidationParameters.pas',
  ClpDsaParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaParameters.pas',
  ClpIDsaParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaParameters.pas',
  ClpDsaPublicKeyParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaPublicKeyParameters.pas',
  ClpIDsaPublicKeyParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaPublicKeyParameters.pas',
  ClpDsaKeyParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaKeyParameters.pas',
  ClpIDsaKeyParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaKeyParameters.pas',
  ClpDsaKeyGenerationParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaKeyGenerationParameters.pas',
  ClpIDsaKeyGenerationParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaKeyGenerationParameters.pas',
  ClpDsaPrivateKeyParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaPrivateKeyParameters.pas',
  ClpIDsaPrivateKeyParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaPrivateKeyParameters.pas',
  ClpDsaKeyPairGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpDsaKeyPairGenerator.pas',
  ClpIDsaKeyPairGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaKeyPairGenerator.pas',
  ClpDsaSigner in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpDsaSigner.pas',
  ClpBase58 in 'additionalUnits\CryptoLib\src\Utils\Encoders\ClpBase58.pas',
  ClpIDsaSigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaSigner.pas',
  ClpDigest in 'additionalUnits\CryptoLib\src\Crypto\Digests\ClpDigest.pas',
  ClpECDHCBasicAgreement in 'additionalUnits\CryptoLib\src\Crypto\Agreement\ClpECDHCBasicAgreement.pas',
  ClpIECDHCBasicAgreement in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECDHCBasicAgreement.pas',
  ClpHMacDsaKCalculator in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpHMacDsaKCalculator.pas',
  ClpIHMacDsaKCalculator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIHMacDsaKCalculator.pas',
  ClpHkdfBytesGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpHkdfBytesGenerator.pas',
  ClpIHkdfBytesGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIHkdfBytesGenerator.pas',
  ClpHkdfParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpHkdfParameters.pas',
  ClpIHkdfParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIHkdfParameters.pas',
  ClpDsaParameterGenerationParameters in 'additionalUnits\CryptoLib\src\Crypto\Parameters\ClpDsaParameterGenerationParameters.pas',
  ClpIDsaParameterGenerationParameters in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaParameterGenerationParameters.pas',
  ClpValidityPrecompInfo in 'additionalUnits\CryptoLib\src\Math\EC\ClpValidityPrecompInfo.pas',
  ClpIValidityPrecompInfo in 'additionalUnits\CryptoLib\src\Interfaces\ClpIValidityPrecompInfo.pas',
  ClpDsaParametersGenerator in 'additionalUnits\CryptoLib\src\Crypto\Generators\ClpDsaParametersGenerator.pas',
  ClpIDsaParametersGenerator in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaParametersGenerator.pas',
  ClpDsaParameter in 'additionalUnits\CryptoLib\src\Asn1\X509\ClpDsaParameter.pas',
  ClpIDsaParameter in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaParameter.pas',
  ClpIPreCompCallBack in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPreCompCallBack.pas',
  ClpNistNamedCurves in 'additionalUnits\CryptoLib\src\Asn1\Nist\ClpNistNamedCurves.pas',
  ClpNat320 in 'additionalUnits\CryptoLib\src\Math\Raw\ClpNat320.pas',
  ClpNat256 in 'additionalUnits\CryptoLib\src\Math\Raw\ClpNat256.pas',
  ClpAesLightEngine in 'additionalUnits\CryptoLib\src\Crypto\Engines\ClpAesLightEngine.pas',
  ClpIAesLightEngine in 'additionalUnits\CryptoLib\src\Interfaces\ClpIAesLightEngine.pas',
  ClpCustomNamedCurves in 'additionalUnits\CryptoLib\src\Crypto\EC\ClpCustomNamedCurves.pas',
  ClpSecP256K1Field in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256K1Field.pas',
  ClpSecP256K1FieldElement in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256K1FieldElement.pas',
  ClpISecP256K1FieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP256K1FieldElement.pas',
  ClpSecP256K1Point in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256K1Point.pas',
  ClpISecP256K1Point in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP256K1Point.pas',
  ClpSecP256K1Curve in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256K1Curve.pas',
  ClpISecP256K1Curve in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP256K1Curve.pas',
  ClpSecP384R1Field in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP384R1Field.pas',
  ClpNat384 in 'additionalUnits\CryptoLib\src\Math\Raw\ClpNat384.pas',
  ClpSecP384R1FieldElement in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP384R1FieldElement.pas',
  ClpISecP384R1FieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP384R1FieldElement.pas',
  ClpSecP384R1Point in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP384R1Point.pas',
  ClpISecP384R1Point in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP384R1Point.pas',
  ClpSecP384R1Curve in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP384R1Curve.pas',
  ClpISecP384R1Curve in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP384R1Curve.pas',
  ClpNat192 in 'additionalUnits\CryptoLib\src\Math\Raw\ClpNat192.pas',
  ClpSecP521R1Field in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP521R1Field.pas',
  ClpNat512 in 'additionalUnits\CryptoLib\src\Math\Raw\ClpNat512.pas',
  ClpSecP521R1FieldElement in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP521R1FieldElement.pas',
  ClpISecP521R1FieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP521R1FieldElement.pas',
  ClpSecP521R1Point in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP521R1Point.pas',
  ClpISecP521R1Point in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP521R1Point.pas',
  ClpSecP521R1Curve in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP521R1Curve.pas',
  ClpISecP521R1Curve in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP521R1Curve.pas',
  ClpInterleave in 'additionalUnits\CryptoLib\src\Math\Raw\ClpInterleave.pas',
  ClpSecT283Field in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecT283Field.pas',
  ClpSecT283FieldElement in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecT283FieldElement.pas',
  ClpISecT283FieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecT283FieldElement.pas',
  ClpSecT283K1Point in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecT283K1Point.pas',
  ClpISecT283K1Point in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecT283K1Point.pas',
  ClpISecT283K1Curve in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecT283K1Curve.pas',
  ClpSecT283K1Curve in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecT283K1Curve.pas',
  ClpSecP256R1Field in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256R1Field.pas',
  ClpSecP256R1FieldElement in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256R1FieldElement.pas',
  ClpISecP256R1FieldElement in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP256R1FieldElement.pas',
  ClpISecP256R1Point in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP256R1Point.pas',
  ClpSecP256R1Point in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256R1Point.pas',
  ClpISecP256R1Curve in 'additionalUnits\CryptoLib\src\Interfaces\ClpISecP256R1Curve.pas',
  ClpSecP256R1Curve in 'additionalUnits\CryptoLib\src\Math\EC\Custom\Sec\ClpSecP256R1Curve.pas',
  ClpIDsaEncoding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaEncoding.pas',
  ClpIDsaExt in 'additionalUnits\CryptoLib\src\Interfaces\ClpIDsaExt.pas',
  ClpStandardDsaEncoding in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpStandardDsaEncoding.pas',
  ClpIStandardDsaEncoding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIStandardDsaEncoding.pas',
  ClpIPlainDsaEncoding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPlainDsaEncoding.pas',
  ClpPlainDsaEncoding in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpPlainDsaEncoding.pas',
  ClpBsiObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Bsi\ClpBsiObjectIdentifiers.pas',
  ClpEacObjectIdentifiers in 'additionalUnits\CryptoLib\src\Asn1\Eac\ClpEacObjectIdentifiers.pas',
  ClpSchnorrDigestSigner in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpSchnorrDigestSigner.pas',
  ClpISchnorrDigestSigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpISchnorrDigestSigner.pas',
  ClpISchnorr in 'additionalUnits\CryptoLib\src\Interfaces\ClpISchnorr.pas',
  ClpECSchnorrSipaSigner in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpECSchnorrSipaSigner.pas',
  ClpIECSchnorrSipaSigner in 'additionalUnits\CryptoLib\src\Interfaces\ClpIECSchnorrSipaSigner.pas',
  ClpISchnorrExt in 'additionalUnits\CryptoLib\src\Interfaces\ClpISchnorrExt.pas',
  ClpISchnorrEncoding in 'additionalUnits\CryptoLib\src\Interfaces\ClpISchnorrEncoding.pas',
  ClpIPlainSchnorrEncoding in 'additionalUnits\CryptoLib\src\Interfaces\ClpIPlainSchnorrEncoding.pas',
  ClpPlainSchnorrEncoding in 'additionalUnits\CryptoLib\src\Crypto\Signers\ClpPlainSchnorrEncoding.pas',
  HlpHash in 'additionalUnits\CryptoLib\src\Base\HlpHash.pas',
  HlpHashBuffer in 'additionalUnits\CryptoLib\src\Base\HlpHashBuffer.pas',
  HlpHashCryptoNotBuildIn in 'additionalUnits\CryptoLib\src\Base\HlpHashCryptoNotBuildIn.pas',
  HlpHashFactory in 'additionalUnits\CryptoLib\src\Base\HlpHashFactory.pas',
  HlpHashResult in 'additionalUnits\CryptoLib\src\Base\HlpHashResult.pas',
  HlpHashRounds in 'additionalUnits\CryptoLib\src\Base\HlpHashRounds.pas',
  HlpHashSize in 'additionalUnits\CryptoLib\src\Base\HlpHashSize.pas',
  HlpHMACNotBuildInAdapter in 'additionalUnits\CryptoLib\src\Base\HlpHMACNotBuildInAdapter.pas',
  HlpKDF in 'additionalUnits\CryptoLib\src\Base\HlpKDF.pas',
  HlpMultipleTransformNonBlock in 'additionalUnits\CryptoLib\src\Base\HlpMultipleTransformNonBlock.pas',
  HlpAdler32 in 'additionalUnits\CryptoLib\src\Checksum\HlpAdler32.pas',
  HlpCRC in 'additionalUnits\CryptoLib\src\Checksum\HlpCRC.pas',
  HlpCRC16 in 'additionalUnits\CryptoLib\src\Checksum\HlpCRC16.pas',
  HlpCRC32 in 'additionalUnits\CryptoLib\src\Checksum\HlpCRC32.pas',
  HlpCRC64 in 'additionalUnits\CryptoLib\src\Checksum\HlpCRC64.pas',
  HlpBlake2B in 'additionalUnits\CryptoLib\src\Crypto\HlpBlake2B.pas',
  HlpBlake2S in 'additionalUnits\CryptoLib\src\Crypto\HlpBlake2S.pas',
  HlpGost in 'additionalUnits\CryptoLib\src\Crypto\HlpGost.pas',
  HlpGOST3411_2012 in 'additionalUnits\CryptoLib\src\Crypto\HlpGOST3411_2012.pas',
  HlpGrindahl256 in 'additionalUnits\CryptoLib\src\Crypto\HlpGrindahl256.pas',
  HlpGrindahl512 in 'additionalUnits\CryptoLib\src\Crypto\HlpGrindahl512.pas',
  HlpHAS160 in 'additionalUnits\CryptoLib\src\Crypto\HlpHAS160.pas',
  HlpHaval in 'additionalUnits\CryptoLib\src\Crypto\HlpHaval.pas',
  HlpMD2 in 'additionalUnits\CryptoLib\src\Crypto\HlpMD2.pas',
  HlpMD4 in 'additionalUnits\CryptoLib\src\Crypto\HlpMD4.pas',
  HlpMD5 in 'additionalUnits\CryptoLib\src\Crypto\HlpMD5.pas',
  HlpMDBase in 'additionalUnits\CryptoLib\src\Crypto\HlpMDBase.pas',
  HlpPanama in 'additionalUnits\CryptoLib\src\Crypto\HlpPanama.pas',
  HlpRadioGatun32 in 'additionalUnits\CryptoLib\src\Crypto\HlpRadioGatun32.pas',
  HlpRadioGatun64 in 'additionalUnits\CryptoLib\src\Crypto\HlpRadioGatun64.pas',
  HlpRIPEMD in 'additionalUnits\CryptoLib\src\Crypto\HlpRIPEMD.pas',
  HlpRIPEMD128 in 'additionalUnits\CryptoLib\src\Crypto\HlpRIPEMD128.pas',
  HlpRIPEMD160 in 'additionalUnits\CryptoLib\src\Crypto\HlpRIPEMD160.pas',
  HlpRIPEMD256 in 'additionalUnits\CryptoLib\src\Crypto\HlpRIPEMD256.pas',
  HlpRIPEMD320 in 'additionalUnits\CryptoLib\src\Crypto\HlpRIPEMD320.pas',
  HlpSHA0 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA0.pas',
  HlpSHA1 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA1.pas',
  HlpSHA2_224 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_224.pas',
  HlpSHA2_256 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_256.pas',
  HlpSHA2_256Base in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_256Base.pas',
  HlpSHA2_384 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_384.pas',
  HlpSHA2_512 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_512.pas',
  HlpSHA2_512_224 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_512_224.pas',
  HlpSHA2_512_256 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_512_256.pas',
  HlpSHA2_512Base in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA2_512Base.pas',
  HlpSHA3 in 'additionalUnits\CryptoLib\src\Crypto\HlpSHA3.pas',
  HlpSnefru in 'additionalUnits\CryptoLib\src\Crypto\HlpSnefru.pas',
  HlpTiger in 'additionalUnits\CryptoLib\src\Crypto\HlpTiger.pas',
  HlpTiger2 in 'additionalUnits\CryptoLib\src\Crypto\HlpTiger2.pas',
  HlpWhirlPool in 'additionalUnits\CryptoLib\src\Crypto\HlpWhirlPool.pas',
  HlpBlake2BConfig in 'additionalUnits\CryptoLib\src\Crypto\Blake2BConfigurations\HlpBlake2BConfig.pas',
  HlpBlake2BIvBuilder in 'additionalUnits\CryptoLib\src\Crypto\Blake2BConfigurations\HlpBlake2BIvBuilder.pas',
  HlpBlake2BTreeConfig in 'additionalUnits\CryptoLib\src\Crypto\Blake2BConfigurations\HlpBlake2BTreeConfig.pas',
  HlpBlake2SConfig in 'additionalUnits\CryptoLib\src\Crypto\Blake2SConfigurations\HlpBlake2SConfig.pas',
  HlpBlake2SIvBuilder in 'additionalUnits\CryptoLib\src\Crypto\Blake2SConfigurations\HlpBlake2SIvBuilder.pas',
  HlpBlake2STreeConfig in 'additionalUnits\CryptoLib\src\Crypto\Blake2SConfigurations\HlpBlake2STreeConfig.pas',
  HlpNullDigest in 'additionalUnits\CryptoLib\src\NullDigest\HlpNullDigest.pas',
  HlpAP in 'additionalUnits\CryptoLib\src\Hash32\HlpAP.pas',
  HlpBernstein in 'additionalUnits\CryptoLib\src\Hash32\HlpBernstein.pas',
  HlpBernstein1 in 'additionalUnits\CryptoLib\src\Hash32\HlpBernstein1.pas',
  HlpBKDR in 'additionalUnits\CryptoLib\src\Hash32\HlpBKDR.pas',
  HlpDEK in 'additionalUnits\CryptoLib\src\Hash32\HlpDEK.pas',
  HlpDJB in 'additionalUnits\CryptoLib\src\Hash32\HlpDJB.pas',
  HlpELF in 'additionalUnits\CryptoLib\src\Hash32\HlpELF.pas',
  HlpFNV in 'additionalUnits\CryptoLib\src\Hash32\HlpFNV.pas',
  HlpFNV1a in 'additionalUnits\CryptoLib\src\Hash32\HlpFNV1a.pas',
  HlpJenkins3 in 'additionalUnits\CryptoLib\src\Hash32\HlpJenkins3.pas',
  HlpJS in 'additionalUnits\CryptoLib\src\Hash32\HlpJS.pas',
  HlpMurmur2 in 'additionalUnits\CryptoLib\src\Hash32\HlpMurmur2.pas',
  HlpMurmurHash3_x86_32 in 'additionalUnits\CryptoLib\src\Hash32\HlpMurmurHash3_x86_32.pas',
  HlpOneAtTime in 'additionalUnits\CryptoLib\src\Hash32\HlpOneAtTime.pas',
  HlpPJW in 'additionalUnits\CryptoLib\src\Hash32\HlpPJW.pas',
  HlpRotating in 'additionalUnits\CryptoLib\src\Hash32\HlpRotating.pas',
  HlpRS in 'additionalUnits\CryptoLib\src\Hash32\HlpRS.pas',
  HlpSDBM in 'additionalUnits\CryptoLib\src\Hash32\HlpSDBM.pas',
  HlpShiftAndXor in 'additionalUnits\CryptoLib\src\Hash32\HlpShiftAndXor.pas',
  HlpSuperFast in 'additionalUnits\CryptoLib\src\Hash32\HlpSuperFast.pas',
  HlpXXHash32 in 'additionalUnits\CryptoLib\src\Hash32\HlpXXHash32.pas',
  HlpFNV1a64 in 'additionalUnits\CryptoLib\src\Hash64\HlpFNV1a64.pas',
  HlpFNV64 in 'additionalUnits\CryptoLib\src\Hash64\HlpFNV64.pas',
  HlpMurmur2_64 in 'additionalUnits\CryptoLib\src\Hash64\HlpMurmur2_64.pas',
  HlpSipHash in 'additionalUnits\CryptoLib\src\Hash64\HlpSipHash.pas',
  HlpXXHash64 in 'additionalUnits\CryptoLib\src\Hash64\HlpXXHash64.pas',
  HlpMurmurHash3_x64_128 in 'additionalUnits\CryptoLib\src\Hash128\HlpMurmurHash3_x64_128.pas',
  HlpMurmurHash3_x86_128 in 'additionalUnits\CryptoLib\src\Hash128\HlpMurmurHash3_x86_128.pas',
  HlpICRC in 'additionalUnits\CryptoLib\src\Interfaces\HlpICRC.pas',
  HlpIHash in 'additionalUnits\CryptoLib\src\Interfaces\HlpIHash.pas',
  HlpIHashInfo in 'additionalUnits\CryptoLib\src\Interfaces\HlpIHashInfo.pas',
  HlpIHashResult in 'additionalUnits\CryptoLib\src\Interfaces\HlpIHashResult.pas',
  HlpIKDF in 'additionalUnits\CryptoLib\src\Interfaces\HlpIKDF.pas',
  HlpIBlake2BConfig in 'additionalUnits\CryptoLib\src\Interfaces\IBlake2BConfigurations\HlpIBlake2BConfig.pas',
  HlpIBlake2BTreeConfig in 'additionalUnits\CryptoLib\src\Interfaces\IBlake2BConfigurations\HlpIBlake2BTreeConfig.pas',
  HlpIBlake2SConfig in 'additionalUnits\CryptoLib\src\Interfaces\IBlake2SConfigurations\HlpIBlake2SConfig.pas',
  HlpIBlake2STreeConfig in 'additionalUnits\CryptoLib\src\Interfaces\IBlake2SConfigurations\HlpIBlake2STreeConfig.pas',
  HlpPBKDF2_HMACNotBuildInAdapter in 'additionalUnits\CryptoLib\src\KDF\HlpPBKDF2_HMACNotBuildInAdapter.pas',
  HlpNullable in 'additionalUnits\CryptoLib\src\Nullable\HlpNullable.pas',
  HlpConverters in 'additionalUnits\CryptoLib\src\Utils\HlpConverters.pas',
  HlpBitConverter in 'additionalUnits\CryptoLib\src\Utils\HlpBitConverter.pas',
  HlpBits in 'additionalUnits\CryptoLib\src\Utils\HlpBits.pas',
  HlpHashLibTypes in 'additionalUnits\CryptoLib\src\Utils\HlpHashLibTypes.pas',
  SbpBase16 in 'additionalUnits\CryptoLib\src\Bases\SbpBase16.pas',
  SbpBase32 in 'additionalUnits\CryptoLib\src\Bases\SbpBase32.pas',
  SbpBase32Alphabet in 'additionalUnits\CryptoLib\src\Bases\SbpBase32Alphabet.pas',
  SbpBase58 in 'additionalUnits\CryptoLib\src\Bases\SbpBase58.pas',
  SbpBase58Alphabet in 'additionalUnits\CryptoLib\src\Bases\SbpBase58Alphabet.pas',
  SbpBase64 in 'additionalUnits\CryptoLib\src\Bases\SbpBase64.pas',
  SbpBase64Alphabet in 'additionalUnits\CryptoLib\src\Bases\SbpBase64Alphabet.pas',
  SbpBase85 in 'additionalUnits\CryptoLib\src\Bases\SbpBase85.pas',
  SbpBase85Alphabet in 'additionalUnits\CryptoLib\src\Bases\SbpBase85Alphabet.pas',
  SbpEncodingAlphabet in 'additionalUnits\CryptoLib\src\Bases\SbpEncodingAlphabet.pas',
  SbpIBase32 in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase32.pas',
  SbpIBase32Alphabet in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase32Alphabet.pas',
  SbpIBase58 in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase58.pas',
  SbpIBase58Alphabet in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase58Alphabet.pas',
  SbpIBase64 in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase64.pas',
  SbpIBase64Alphabet in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase64Alphabet.pas',
  SbpIBase85 in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase85.pas',
  SbpIBase85Alphabet in 'additionalUnits\CryptoLib\src\Interfaces\SbpIBase85Alphabet.pas',
  SbpIEncodingAlphabet in 'additionalUnits\CryptoLib\src\Interfaces\SbpIEncodingAlphabet.pas',
  SbpBits in 'additionalUnits\CryptoLib\src\Utils\SbpBits.pas',
  SbpSimpleBaseLibTypes in 'additionalUnits\CryptoLib\src\Utils\SbpSimpleBaseLibTypes.pas',
  SbpUtilities in 'additionalUnits\CryptoLib\src\Utils\SbpUtilities.pas';


{$R *.res}

var
  H: THandle;

begin

  VKAutoShowMode := TVKAutoShowMode.Never;

  FMX.Types.GlobalUseDX := true;

  GlobalUseDXInDX9Mode := true;
  GlobalUseDXSoftware := true;
  FMX.Types.GlobalDisableFocusEffect := true;
{$IF NOT DEFINED(LINUX)}
  H := CreateMutex(nil, False, 'HODLERTECHMUTEX');
  if (H <> 0) and (GetLastError <> ERROR_ALREADY_EXISTS) then
  begin
    try
      Application.Initialize;

      Application.FormFactor.Orientations := [TFormOrientation.Portrait];
      Application.CreateForm(TfrmHome, frmHome);
      Application.Run;
    finally
      ReleaseMutex(H);
    end;
  end;
  CloseHandle(H);
{$ENDIF}
{$IF DEFINED(LINUX)}
  Application.Initialize;

  Application.FormFactor.Orientations := [TFormOrientation.Portrait];
  Application.CreateForm(TfrmHome, frmHome);
  Application.Run;
{$ENDIF}

end.
